workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        GRADLE_TASK: assembleRelease
      java: 17
      android:
        build_tools_version: "34.0.0"
        compile_sdk_version: 34
        target_sdk_version: 34
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew $GRADLE_TASK
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"
