workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      java: 17
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew

      - name: Auto download gradle-wrapper.jar if missing
        script: |
          if [ ! -f android/gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found. Downloading gradle zip..."
            curl -O https://services.gradle.org/distributions/gradle-8.4-bin.zip
            unzip -q gradle-8.4-bin.zip
            cp gradle-8.4/lib/gradle-wrapper.jar android/gradle/wrapper/
            echo "gradle-wrapper.jar downloaded and placed."
          else
            echo "gradle-wrapper.jar already exists."
          fi

      - name: Build APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/**/*.apk
