workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      android_signing:
        - Roshan Gani
    scripts:
      - name: Give gradlew permission
        script: chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
