workflows:
  react-native-android:
    name: React Native Android APK Build (Public Repo - No Git Push)
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      android_signing:
        - Roshan Gani
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ExaQuiz_Android_Codemagic_Ready/gradlew
      - name: Install dependencies
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          npm install --legacy-peer-deps
      - name: Build APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk
