workflows:
  react-native-android:
    name: React Native Android APK Build
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      node: 16.20.0
      java: 17
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./ExaQuiz_Android_Codemagic_Ready/android/gradlew

      - name: Build APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          ./gradlew assembleRelease

    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/**/*.apk
