workflows:
  android-app:
    name: ExaQuiz Free Build
    instance_type: linux  # ✅ Free tier-compatible
    environment:
      java: 17
      vars:
        PROJECT_DIR: "ExaQuiz_Android_Codemagic_Ready"
    scripts:
      - name: Make gradlew executable
        script: |
          cd $PROJECT_DIR/android
          chmod +x ./gradlew
      - name: Build APK
        script: |
          cd $PROJECT_DIR/android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/**/*.apk
