workflows:
  release-build:
    name: Build Release APK
    instance_type: linux_x2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      vars:
        GRADLE_TASK: "assembleRelease"
    scripts:
      - name: Grant execute permission to gradlew
        script: chmod +x ./gradlew
      - name: Run Gradle build
        script: ./gradlew $GRADLE_TASK
    artifacts:
      - android/app/build/outputs/**/*.apk
