workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        JAVA_VERSION: 17
      node: 18.16.0
      java: 17
      android: sdk
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
