workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
    working_directory: ExaQuiz_Android_Codemagic_Ready
    scripts:
      - name: Set up GitHub token (⚠️ Not Secure)
        script: |
          git config --global url."https://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@github.com/".insteadOf "https://github.com/"
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Make gradlew executable
        script: |
          chmod +x gradlew
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
