workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      groups:
        - github_access
      android_signing:
        - your_keystore_reference  # (optional: agar signing kar rahe ho)
    scripts:
      - name: Install Node & Dependencies
        script: |
          npm install
      - name: Make gradlew executable
        script: |
          chmod +x ./ExaQuiz_Android_Codemagic_Ready/gradlew
      - name: Build Android APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          ./gradlew assembleRelease
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
