workflows:
  react-native-android:
    name: ExaQuiz Android APK Build
    instance_type: linux  # ✅ FREE PLAN SUPPORTED
    environment:
      java: 17
      vars:
        PROJECT_DIR: "ExaQuiz_Android_Codemagic_Ready"
    scripts:
      - name: Make gradlew executable
        script: |
          cd $PROJECT_DIR/android
          chmod +x ./gradlew
      - name: Build APK
        script: |
          cd $PROJECT_DIR/android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/**/*.apk
