workflows:
  react-native-android:
    name: Build React Native Android APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz" # <-- replace this with your actual package name
      node: 16
      java: 17
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Make gradlew executable
        script: chmod +x android/gradlew
      - name: Build Android APK
        script: cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
