workflows:
  react-native-android:
    name: React Native Android Build
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
