workflows:
  react-native-android:
    name: Build React Native Android App
    instance_type: linux  # ✅ FREE plan compatible
    environment:
      vars:
        JAVA_HOME: /opt/java/openjdk
    scripts:
      - name: Make gradlew executable
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          chmod +x ./gradlew
      - name: Build APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/**/*.apk
