workflows:
  build-android:
    name: Build Android APK (Free Plan)
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      android_signing:
        - Roshan Gani
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
