workflows:
  react-native-android:
    name: React Native Android Build

    environment:
      node: 16.20.0
      groups:
        - github_access  # ✅ Make sure this group contains GITHUB_TOKEN
      android_signing:
        - Roshan Gani     # ✅ Reference name of the uploaded keystore
    working_directory: ExaQuiz_Android_Codemagic_Ready

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Build APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
