workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
    working_directory: ExaQuiz_Android_Codemagic_Ready
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
          ls -la ./gradlew

      - name: Build APK
        script: |
          ./gradlew assembleRelease --stacktrace --info

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
