workflows:
  exaquiz-android-build:
    name: ExaQuiz Android Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.android"
        KEYSTORE_PASSWORD: EncryptedKeystorePassword
        KEY_ALIAS: exaquiz_key
        KEY_PASSWORD: EncryptedKeyPassword
      android_signing:
        keystore_reference: exaquiz_keystore
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
