workflows:
  react-native-android:
    name: React Native Android Workflow
    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 16.20.0
      java: 17
      node: 16.20.0

    scripts:
      - name: Install npm dependencies
        working_directory: ExaQuiz_Android_Codemagic_Ready
        script: |
          npm install

      - name: Give gradlew permission
        working_directory: ExaQuiz_Android_Codemagic_Ready/android
        script: |
          chmod +x gradlew

      - name: Run Gradle build
        working_directory: ExaQuiz_Android_Codemagic_Ready/android
        script: |
          ./gradlew assembleRelease

    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/apk/release/*.apk
