workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      android_signing:
        - Roshan Gani
    scripts:
      - name: ✅ Check & Make gradlew executable
        script: |
          if [ -f "ExaQuiz_Android_Codemagic_Ready/gradlew" ]; then
            chmod +x ExaQuiz_Android_Codemagic_Ready/gradlew
          else
            echo "❌ gradlew file not found!"
            exit 1
          fi
      - name: 📦 Install npm dependencies
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          npm install --legacy-peer-deps
      - name: 🛠 Build Android APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
