workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      # सुनिश्चित करें कि तुमने Codemagic UI में 'my_github_pat' नाम का Environment Variable Group
      # बनाया है और उसमें 'GIT_ACCESS_TOKEN' नाम का वेरिएबल है जिसमें तुम्हारा GitHub PAT है।
      groups:
        - my_github_pat 
      android_signing:
        - Roshan Gani # तुम्हारी Android Signing Key का नाम
    
    # यह वह डायरेक्टरी है जहाँ Codemagic तुम्हारे प्रोजेक्ट के अंदर काम करेगा।
    # यह सीधे तुम्हारे GitHub रेपो के अंदर वाले 'ExaQuiz_Android_Codemagic_Ready' फोल्डर को पॉइंट कर रहा है।
    # Codemagic को यह एक्सपेक्ट करना चाहिए कि क्लोन किया गया रेपो इसी फोल्डर स्ट्रक्चर में आएगा।
    working_directory: ExaQuiz-Android-App/ExaQuiz_Android_Codemagic_Ready
    
    scripts:
      # हम 'rm -rf' वाले स्टेप्स हटा रहे हैं क्योंकि Codemagic का बिल्ड एनवायरनमेंट हर बार फ्रेश होता है।
      # Git clone की लाइन भी हटा रहे हैं क्योंकि Codemagic को उसे खुद ही करना चाहिए
      # अगर GitHub App integration काम नहीं कर रहा है, और PAT मौजूद है, तो Codemagic
      # अपने आप इसे इस्तेमाल करके क्लोन करने की कोशिश करेगा।
      
      - name: Install Node dependencies
        script: |
          npm install --legacy-peer-deps
      
      - name: Make gradlew executable
        script: |
          # यह कमांड 'ExaQuiz-Android-App/ExaQuiz_Android_Codemagic_Ready' के अंदर चलेगा।
          # सुनिश्चित करें कि 'gradlew' फाइल यहीं पर है।
          chmod +x ./gradlew
      
      - name: Build Android APK
        script: |
          ./gradlew assembleRelease --no-daemon
          
    artifacts:
      # यह artifacts का पाथ है, जो 'working_directory' के सापेक्ष (relative) है।
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - your_email@example.com # यहाँ अपनी ईमेल ID डालें
        notify:
          success: true
          failure: true
