workflows:
  react-native-android:
    name: React Native Android APK Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      android_signing:
        - Roshan Gani  # ✅ yahi sahi naam hai
      node: 16.20.0
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - roshangani@email.com
        notify:
          success: true
          failure: true
