workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
      android_signing:
        - Roshan Gani
    working_directory: ExaQuiz_Android_Codemagic_Ready
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew  # <-- FIXED PATH

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
