workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
      android_signing:
        - keystore: exaquiz-keystore
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Make gradlew executable
        script: chmod +x android/gradlew
      - name: Build APK
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
