workflows:
  react-native-android:
    name: Build React Native Android App
    instance_type: mac_mini
    environment:
      vars:
        JAVA_HOME: /opt/java/openjdk
    triggering:
      events:
        - push
    scripts:
      - name: Build APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/**/*.apk
