workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0

    scripts:
      - name: Install Node dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          chmod +x ./ExaQuiz_Android_Codemagic_Ready/gradlew

      - name: Build Android APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
