workflows:
  react-native-android:
    name: React Native Android Workflow
    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 16.20.0
        FLUTTER_CHANNEL: stable
      java: 17
      node: 16.20.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Run Gradle build
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
