workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 30
    environment:
      instance_type: linux  # 👈 Yahi pehle galat tha: mac_mini
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      flutter: stable
      node: 16
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set Gradle wrapper permission
        script: |
          chmod +x android/gradlew
      - name: Build release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
