workflows:
  react-native-android:
    name: React Native Android APK Build (Public Repo - No Git Push)
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      android_signing:
        - Roshan Gani
    scripts:
      - name: 🛠 Build Android APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
