workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      groups:
        - github_access   # ✅ Tumhara saved group jisme GITHUB_TOKEN hai
      node: 16.20.0
      android_signing:
        - Roshan Gani  # ✅ If you're using signing
    working_directory: ExaQuiz_Android_Codemagic_Ready
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Build APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
