workflows:
  react-native-android:
    name: Build React Native Android APK with Auto Jar Download
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.yourapp" # 👈 Replace with your actual package name
      node: 18.16.0
      java: 17
    scripts:
      - name: Install Dependencies
        script: |
          npm install

      - name: Make gradlew executable
        script: |
          chmod +x android/gradlew

      - name: Auto-download gradle-wrapper.jar if missing
        script: |
          if [ ! -f android/gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Downloading gradle-wrapper.jar..."
            curl -o android/gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar
          else
            echo "gradle-wrapper.jar already exists."
          fi

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/**/*.apk
