workflows:
  android-build:
    name: Android APK Build for React Native
    max_build_duration: 60
    environment:
      node: 18.16.0
      java: 17
      vars:
        PACKAGE_NAME: "com.exaquiz.app"   # â† yeh tumhara Android package name hai
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
