workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      groups:
        - github_access
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ./ExaQuiz_Android_Codemagic_Ready/gradlew
      - name: Build APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          ./gradlew assembleRelease
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk
