workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
      android_signing:
        - keystore: Roshan Gani
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Convert gradlew to LF
        script: dos2unix Android/ExaQuiz_Android_Codemagic_Ready/gradlew
      - name: Make gradlew executable
        script: chmod +x Android/ExaQuiz_Android_Codemagic_Ready/gradlew
      - name: Build APK
        script: cd Android/ExaQuiz_Android_Codemagic_Ready && ./gradlew assembleRelease
    artifacts:
      - Android/ExaQuiz_Android_Codemagic_Ready/app/build/outputs/apk/release/*.apk
