workflows:
  react-native-android:
    name: Manual Clone + Android Build
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      android_signing:
        - Roshan Gani

    scripts:
      - name: Manually clone the repo
        script: |
          rm -rf ExaQuiz_Android_Codemagic_Ready
          git clone https://github.com/ExaQuiz/ExaQuiz-Android-App.git
          cd ExaQuiz-Android-App
          mv ExaQuiz_Android_Codemagic_Ready ../
          cd ..
          rm -rf ExaQuiz-Android-App

      - name: Install Node dependencies
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          chmod +x ./gradlew

      - name: Build Android APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
