workflows:
  android-app:
    name: ExaQuiz Build
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      android_signing:
        - exaquiz_keystore
      java: 17
    scripts:
      - name: Set executable permission for gradlew
        script: |
          chmod +x ./gradlew
      - name: Build release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk
