# ... बाकी YAML ...
environment:
  # ... बाकी environment variables ...
  groups:
    - my_github_token_group # यहाँ आपके नए ग्रुप का नाम
  # ...
scripts:
  - name: Remove existing source code
    script: |
      rm -rf ./*
  - name: Clone repository using PAT
    script: |
      git clone https://oauth2:${GIT_ACCESS_TOKEN}@github.com/ExaQuiz/ExaQuiz-Android-App.git .
  - name: Install Node dependencies
    script: |
      npm install --legacy-peer-deps
  # ... बाकी स्क्रिप्ट्स ...
