workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      node: 16.14.2
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set Gradle wrapper permission
        script: |
          chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
