workflows:
  react-native-android:
    name: React Native Android Workflow
    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 16.20.0
        FLUTTER_CHANNEL: stable
      java: 17
      node: 16.20.0
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - node_modules
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - ExaQuiz_Android_Codemagic_Ready/android/app/build/outputs/**/*.apk
