workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.exaquizapp"   # â† apna package name yaha daalo
      node: 18.16.0
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set up Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
