workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      groups:
        - my_github_pat
      android_signing:
        - Roshan Gani

    working_directory: ExaQuiz_Android_Codemagic_Ready/android

    scripts:
      - name: Install Node dependencies
        script: |
          #!/usr/bin/env bash
          npm install --legacy-peer-deps --loglevel verbose

      - name: Make gradlew executable
        script: |
          #!/usr/bin/env bash
          chmod +x ./gradlew

      - name: Build Android APK
        script: |
          #!/usr/bin/env bash
          ./gradlew assembleRelease --no-daemon
