workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        GRADLE_TASK: assembleRelease
    scripts:
      - name: Set gradlew as executable
        script: chmod +x ./android/gradlew
      - name: Build APK
        script: cd android && ./gradlew $GRADLE_TASK
    artifacts:
      - android/app/build/outputs/**/*.apk
