workflows:
  react-native-android:
    name: React Native Android APK Build (Public Repo - No Git Push)
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      android_signing:
        - Roshan Gani
    scripts:
      - name: Make gradlew executable
        script: |
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          else
            echo "❌ gradlew file not found in android/"
            exit 1
          fi
      - name: Install dependencies
        script: |
          cd android
          npm install --legacy-peer-deps
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
