workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
      android_signing:
        - Roshan Gani
    working_directory: ExaQuiz_Android_Codemagic_Ready/android
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Check files (debugging)
        script: |
          ls -al
          ls -al ./app

      - name: Build APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk
