workflows:
  android-app-build:
    name: Android APK Build with Auto Jar Download
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      java: "$JAVA_VERSION"
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Auto download gradle-wrapper.jar if missing
        script: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar not found. Downloading gradle zip..."
            curl -O https://services.gradle.org/distributions/gradle-8.4-bin.zip
            unzip -q gradle-8.4-bin.zip
            cp gradle-8.4/lib/gradle-wrapper.jar gradle/wrapper/
            echo "gradle-wrapper.jar downloaded and placed."
          else
            echo "gradle-wrapper.jar already exists."
          fi

      - name: Build APK
        script: |
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - build/app/outputs/**/*.apk
