workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
    scripts:
      - name: Build Release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
