workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
      android_signing:
        - keystore: Roshan Gani
    working_directory: Android/ExaQuiz_Android_Codemagic_Ready
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - Android/ExaQuiz_Android_Codemagic_Ready/app/build/outputs/apk/release/*.apk
