workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      node: 16.20.0
      android_signing:
        - Roshan Gani  # <- Keystore ka reference name (Codemagic UI se)
    working_directory: ExaQuiz_Android_Codemagic_Ready/android
    scripts:
      - name: Install dependencies
        script: |
          cd ..
          npm install --legacy-peer-deps

      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Build APK
        script: |
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - app/build/outputs/apk/release/*.apk
