workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      java: 17
      node: 16.20.0
      # सुनिश्चित करें कि तुमने Codemagic UI में 'my_github_pat' नाम का Environment Variable Group
      # बनाया है और उसमें 'GIT_ACCESS_TOKEN' नाम का वेरिएबल है जिसमें तुम्हारा GitHub PAT है।
      groups:
        - my_github_pat 
      android_signing:
        - Roshan Gani # तुम्हारी Android Signing Key का नाम
    
    # वर्किंग डायरेक्टरी को रेपो के रूट में सेट करो।
    # हम बाद में प्रोजेक्ट फोल्डर में नेविगेट करेंगे।
    working_directory: . 
    
    scripts:
      # यह स्टेप Codemagic द्वारा क्लोन किए गए रेपो को हटा देगा, अगर यह मौजूद है।
      # `|| true` इसे फेल होने पर भी स्क्रिप्ट को जारी रखने देगा।
      - name: Clean up existing repository clone
        script: |
          rm -rf ExaQuiz-Android-App || true
          
      # अब पूरे GitHub रेपो को क्लोन करते हैं। यह रेपो के रूट में क्लोन होगा।
      - name: Clone repository using PAT
        script: |
          git clone https://oauth2:${GIT_ACCESS_TOKEN}@github.com/ExaQuiz/ExaQuiz-Android-App.git
          
      # अब हम क्लोन किए गए रेपो के अंदर सही प्रोजेक्ट फोल्डर में जाते हैं।
      - name: Navigate to project directory
        script: |
          cd ExaQuiz-Android-App/ExaQuiz_Android_Codemagic_Ready
          
      - name: Install Node dependencies
        script: |
          npm install --legacy-peer-deps
      
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      
      - name: Build Android APK
        script: |
          ./gradlew assembleRelease --no-daemon
          
    artifacts:
      - ExaQuiz-Android-App/ExaQuiz_Android_Codemagic_Ready/app/build/outputs/**/*.apk # artifacts पाथ अपडेट किया गया
      
    publishing:
      email:
        recipients:
          - your_email@example.com # यहाँ अपनी ईमेल ID डालें
        notify:
          success: true
          failure: true
