workflows:
  react-native-android:
    name: React Native Android Build
    # ❌ Remove this line 👇
    # instance_type: linux
    environment:
      java: 17
    scripts:
      - name: Make gradlew executable
        script: |
          cd android
          chmod +x ./gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
