workflows:
  debug-build:
    name: Build Debug APK (No Signing)
    max_build_duration: 60
    environment: {}
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
