workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: "/opt/java/openjdk"
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Android dependencies
        script: |
          cd android
          ./gradlew dependencies
      - name: Build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
