scripts:
  - name: Make gradlew executable
    script: |
      chmod +x ExaQuiz_Android_Codemagic_Ready/gradlew
  - name: Install dependencies
    script: |
      cd ExaQuiz_Android_Codemagic_Ready
      npm install --legacy-peer-deps
  - name: Build APK
    script: |
      cd ExaQuiz_Android_Codemagic_Ready
      ./gradlew assembleRelease --no-daemon
