workflows:
  react-native-android:
    name: React Native Android Workflow
    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 16.20.0
      java: 17
      node: 16.20.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Give gradlew permission
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          chmod +x gradlew
      - name: Run Gradle build
        script: |
          cd ExaQuiz_Android_Codemagic_Ready/android
          ./gradlew assembleRelease
    artifacts:
      - '**/app-release.apk'
