workflows:
  build-android:
    name: Build release APK
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      node: 16.13.1
    scripts:
      - name: Set Gradle wrapper permission
        script: |
          cd android
          chmod +x gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
