workflows:
  react-native-android:
    name: React Native Android APK Build
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"  # <- change if needed
      node: 16.13.1
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set Gradle wrapper permission
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/**/*.apk
